

function scrollToMap() {
    var mapSection = document.getElementById("mapa");
    mapSection.scrollIntoView({ behavior: "smooth" });
}


function scrollToMeet() {
    var mapSection = document.getElementById("encontros");
    mapSection.scrollIntoView({ behavior: "smooth" });
}

function scrollToCadastro() {
    var mapSection = document.getElementById("cadastro");
    mapSection.scrollIntoView({ behavior: "smooth" });
}